## Configuration for the training, evaluation
samples:
  - name: 4top
    label: 2
    path: /users/yewzzang/TTTT_TuneCP5_13TeV-amcatnlo-pythia8/4top_dump_ex1/220324_055935/graph/4top_ex1_9*.h5
    xsec: 0.012
    ngen: 11952188

#   - name: 4top
#     label: 2
#     path: /users/yewzzang/TTTT_TuneCP5_13TeV-amcatnlo-pythia8/4top_dump_ex1/220323_084833/graph/4top_ex1_9*.h5
#     xsec: 0.012
#     ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0, 0] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
